Update controls.py
Fix issue of https://github.com/brainpy/BrainPy/issues/455. The ``lambda _: 1`` needs a input.
By default, the input is ``operands=None``, then updated to tuple() by 
```python
  if operands is None:
    operands = tuple()
```
However, even 
```python
func = lambda _:1
func(tuple())
```
works, BrainPy still get an error as ``TypeError: <lambda>() missing 1 required positional argument: '_'``

There are ways to fix this error, changing the default value of operands to be ``operands = 1`` or  ``operands = (1)`` etc, all works. But the same method in function cond(..., operands = ()) doesn't work either. It seems empty tuple or list cannot be recognized.